homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: metric
  elevation: 0
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Europe/Amsterdam
  packages:
    vacation: !include packages/vacation.yaml

default_config:
group:          !include_dir_merge_named groups
stream:

hue:
  bridges:
    - host: !secret hue.ip
      allow_unreachable: true
      allow_hue_groups: true

sensor:
  - platform: growatt_server
    username: !secret growatt.user
    password: !secret growatt.pass
  
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'home-assistant/home-assistant'
      - path: 'containous/traefik'
# http:
# frontend:

person:
  - name: mans
    id: !secret mans.id
    device_trackers:
      - device_tracker.iphone_van_mans
      - device_tracker.iphone_van_mans_2
  - name: rianne
    id: !secret rianne.id
    device_trackers:
      - device_tracker.cat7
      - device_tracker.cat7_2

media_player:
  - platform: webostv
    host: !secret tv.ip

lovelace:
  mode: yaml

notify:
  - platform: webostv
    host: !secret tv.ip
    name: woonkamertv
    filename: webostv.conf

camera:
  - platform: generic
    name: camera
    still_image_url: !secret camera.snap
    stream_source: !secret camera.url
    verify_ssl: false
  
mqtt:
  broker: !secret mqtt.ip