homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: metric
  elevation: 0
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Europe/Amsterdam

default_config:

hue:
  bridges:
    - host: !secret hue.ip
      allow_unreachable: true
      allow_hue_groups: true

sensor:
  - platform: growatt_server
    username: !secret growatt.user
    password: !secret growatt.pass
# http:
# frontend:

person:
  - name: mans
    id: mans123
    device_trackers:
      - device_tracker.iphone_van_mans
      - device_tracker.iphone_van_mans_2
  - name: rianne
    id: rw123
    device_trackers:
      - device_tracker.cat7

# unifi:
#   controllers:
#     - host: !secret unifi.ip
#       site: !secret unifi.site
#       ssid_filter:
#         - 'HomeSSID'
#         - 'IoTSSID'