homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: metric
  elevation: 0
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Europe/Amsterdam

default_config:

hue:
  bridges:
    - host: !secret hue.ip
      allow_unreachable: true
      allow_hue_groups: true

sensor:
  - platform: growatt_server
    username: !secret growatt.user
    password: !secret growatt.pass
# http:
# frontend:

person:
  - name: mans
    id: !secret mans.id
    device_trackers:
      - device_tracker.iphone_van_mans
      - device_tracker.iphone_van_mans_2
  - name: rianne
    id: !secret rianne.id
    device_trackers:
      - device_tracker.cat7
      - device_tracker.cat7_2

media_player:
  - platform: webostv
    host: !secret tv.ip

lovelace:
  mode: yaml