homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: metric
  elevation: 0
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages
  customize: !include customize.yaml

default_config:
group:          !include_dir_merge_named groups
stream:

hue:
  bridges:
    - host: !secret hue.ip
      allow_unreachable: true
      allow_hue_groups: true

sensor:
  - platform: growatt_server
    username: !secret growatt.user
    password: !secret growatt.pass
  
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'home-assistant/home-assistant'
      - path: 'containous/traefik'

  - platform: thinkingcleaner
    host: 10.0.2.206

  - platform: netdata
    host: '10.0.2.24'
    port: '19999'
    name: r710top
    resources:
      cpu:
        data_group: system.cpu
        element: idle
        invert: true
# http:
# frontend:
switch:
  - platform: thinkingcleaner
    host: 10.0.2.206

person:
  - name: mans
    id: !secret mans.id
    device_trackers:
      - device_tracker.iphone_van_mans
      - device_tracker.iphone_van_mans_2
  - name: rianne
    id: !secret rianne.id
    device_trackers:
      - device_tracker.cat7

webostv:
  name: Woonkamer TV
  host: !secret tv.ip

  # - platform: denon
  #   name: marantz_sr7005
  #   host: !secret marantz.ip
  #   #mac: !secret marantz.mac

lovelace:
  mode: yaml

# notify:
#   - platform: webostv
#     host: !secret tv.ip
#     name: media_player.woonkamer_tv
#     filename: webostv.conf

camera:
  - platform: generic
    name: camera
    still_image_url: !secret camera.snap
    stream_source: !secret camera.url
    verify_ssl: false
  
mqtt:
  broker: mosquitto.mqtt.svc
  discovery: true

octoprint:
  host: !secret octoprint.host
  api_key: !secret octoprint.apikey
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Temperatures'
      - 'Time Elapsed'
      - 'Time Remaining'

plant:
  keuken_plant:
    sensors:
      moisture: sensor.mi_flora_moisture
      battery: sensor.mi_flora_battery
      temperature: sensor.mi_flora_temperature
      conductivity: sensor.mi_flora_conductivity
      brightness: sensor.mi_flora_light_intensity
    min_moisture: 20

cast:
  media_player:
    - host: 10.0.2.75

recorder:
  purge_keep_days: 14
  db_url: !secret postgres.url
  db_max_retries: 50
  db_retry_wait: 10

  