title: Thuis
# Include external resources
# resources:
#   - url: /local/my-custom-card.js
#     type: js
#   - url: /local/my-webfont.css
#     type: css

views:
    # View tab title.
  - title: Thuis
    # Unique path for direct access /lovelace/${path}
    path: thuis
    cards:
      - title: Lights
        type: entities
        entities:
          - group.tv
          - group.salontafel
          - group.eettafel
        show_header_toggle: false

      - title: Weer thuis
        type: weather-forecast
        entity: weather.thuis

      - type: horizontal-stack
        title: Locaties
        show_header_toggle: false
        cards:
        - title: Mans
          type: entities
          entities:
            - entity: person.mans
            - entity: sensor.battery_level
          show_header_toggle: false
          
        - title: Rianne
          type: entities
          entities:
            - entity: person.rianne_2
            - entity: sensor.battery_level_2
          show_header_toggle: false

      - title: Solar Panels
        type: entities
        entities:
        - entity: sensor.growatt_total_energy_today
        - entity: sensor.growatt_total_output_power
        - entity: sensor.growatt_total_lifetime_energy_output
        show_header_toggle: false

      - title: Woonkamer tv
        type: media-control
        entity: media_player.lg_webos_smart_tv

      - type: picture-glance
        title: Voordeur
        entities: []
        camera_image: camera.camera


  - icon: mdi:lightbulb-multiple
    title: Lights
    cards:
      - title: TV
        type: entities
        entities:
          - light.ikea_links
          - light.ikea_rechts_nieuw
      
      - title: Salontafel
        type: entities
        entities:
          - light.plafondlamp
      
      - title: Eettafel
        type: entities
        entities:
          - light.hue_color_pendant_down_1
          - light.hue_color_pendant_up_1

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Misc
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: switches
        show_header_toggle: false
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - input_boolean.vak_mode
      #     - switch.ac
      #     - entity: light.living_room
      #       # Override the name to use
      #       name: LR Lights
      - type: plant-status
        entity: plant.keuken_plant
      #   # The markdown card will render markdown text.
      # - type: markdown
      #   title: Lovelace
      #   content: >
      #     Welcome to your **Lovelace UI**.