title: Thuis
# Include external resources
# resources:
#   - url: /local/my-custom-card.js
#     type: js
#   - url: /local/my-webfont.css
#     type: css

views:
    # View tab title.
  - title: Thuis
    # Unique path for direct access /lovelace/${path}
    path: thuis
    cards:
      - title: Lights
        type: entities
        entities:
          - group.tv
          - group.salontafel
          - group.eettafel
        show_header_toggle: false

      - title: Temperatuur Woonkamer
        type: entities
        show_header_toggle: false
        entities:
          - entity: !secret zwave.rookmelder_temp
            name: Rookmelder
            icon: mdi:smoke-detector
          - entity: sensor.mi_flora_temperature
            name: Mi Flora
            icon: mdi:flower

      - title: Weer thuis
        type: weather-forecast
        entity: weather.thuis

      - type: horizontal-stack
        title: Locaties
        show_header_toggle: false
        cards:
        - title: Mans
          type: entities
          entities:
            - entity: person.mans
            - entity: sensor.battery_level
          show_header_toggle: false
          
        - title: Rianne
          type: entities
          entities:
            - entity: person.rianne_2
            - entity: sensor.battery_level_2
          show_header_toggle: false

      - title: Solar Panels
        type: entities
        entities:
        - entity: sensor.growatt_total_energy_today
        - entity: sensor.growatt_total_output_power
        - entity: sensor.growatt_total_lifetime_energy_output
        show_header_toggle: false

      - title: Woonkamer tv
        type: media-control
        entity: media_player.woonkamer_tv

      - type: picture-glance
        title: Voordeur
        entities: []
        camera_image: camera.camera


  - icon: mdi:lightbulb-multiple
    title: Lights
    cards:
      - title: TV
        type: entities
        entities:
          - light.ikea_links
          - light.ikea_rechts_nieuw
      
      - title: Salontafel
        type: entities
        entities:
          - light.plafondlamp
      
      - title: Eettafel
        type: entities
        entities:
          - light.hue_color_pendant_down_1
          - light.hue_color_pendant_up_1

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Misc
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: switches
        show_header_toggle: false
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - input_boolean.vak_mode
          - input_boolean.restart_marantz
      #     - switch.ac
      #     - entity: light.living_room
      #       # Override the name to use
      #       name: LR Lights

      - type: entities
        title: roomba
        show_header_toggle: false
        entities:
          - sensor.roomba_state
          - sensor.roomba_battery
          - sensor.roomba_capacity
          - switch.roomba_clean
          - switch.roomba_dock
          - switch.roomba_find

      - type: plant-status
        entity: plant.keuken_plant
        name: Paprika (keuken)

      - type: entities
        title: wasmachine
        show_header_toggle: false
        entities:
          - sensor.wasmachine_status
          - switch.nodeid_11_switch

      - type: entities
        id: octoprint
        title: OctoPrint
        show_header_toggle: false
        entities:
          - input_boolean.3dprinter
          - binary_sensor.octoprint_printing
          - binary_sensor.octoprint_printing_error
          - entity: sensor.octoprint_current_state
            secondary_info: last-changed
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_remaining_format
          - sensor.octoprint_time_elapsed_format
          - entity: !secret zwave.sensor_node10
            name: Power Usage
            icon: mdi:flash
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_target_tool0_temp

      - type: conditional
        conditions:
          - entity: input_boolean.3dprinter
            state: "on"
        card:
          type: picture-glance
          title: Octoprint
          entities: []
          camera_image: camera.octoprint
        
      #   # The markdown card will render markdown text.
      # - type: markdown
      #   title: Lovelace
      #   content: >
      #     Welcome to your **Lovelace UI**.