input_boolean:
  3dprinter:
    name: 3D Printer
    #initial: off
    icon: mdi:printer-3d

automation:
  - alias: 3dprinter_on
    trigger: 
      - platform: state
        entity_id: input_boolean.3dprinter
        from: 'off'
        to: 'on'
        for:
          seconds: 10
    action:
      - service: switch.turn_on
        entity_id: switch.nodeid_10_switch
      - service: switch.turn_on
        entity_id: switch.octopi
      
  - alias: 3dprinter_off
    trigger: 
      - platform: state
        entity_id: input_boolean.3dprinter
        from: 'on'
        to: 'off'
        for:
          seconds: 30
    action:
      - service: shell_command.shutdown_octopi
      - delay: '00:01:00'
      - service: switch.turn_off
        entity_id: switch.nodeid_10_switch
      - service: switch.turn_off
        entity_id: switch.octopi

shell_command:
  shutdown_octopi: !secret octoprint.shutdown
