automation:
  - alias: 'Growatt state'
    trigger:
      platform: template
      value_template: "{{ now().timestamp() - states.sensor.growatt_total_output_power.last_updated.timestamp() > 900 }}"
    condition:
      - condition: sun
        after: sunrise
        before: sunset
    action:
      - service: persistent_notification.create
        data:
          title: 'Growatt value is stale.'
          message: 'Value has not been updated in over 900 seconds.'
      - service: rest_command.reload_growatt
        data: {}
  
  # - alias: 'Restart HA'
  #   trigger:
  #     platform: time
  #     at: '3:30:00'
  #   action:
  #     - service: homeassistant.restart

  - alias: KLF reboot on hass stop event
    description: Reboots the KLF200 in order to avoid SSL Handshake issue
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - service: velux.reboot_gateway
      
  - alias: 'Restart velux nacht'
    trigger:
      platform: time
      at: '3:30:00'
    action:
      - service: velux.reboot_gateway

  # - alias: 'Restart velux dag'
  #   trigger:
  #     platform: time
  #     at: '15:30:00'
  #   action:
  #     - service: velux.reboot_gateway


rest_command:
  reload_growatt:
    url: !secret growatt.reloadurl
    method: POST
    headers:
      authorization: !secret restart.token
      content-type: application/json

